@startuml
if (loanCount?) equals (has 1 loan) then
  :check loan has autopay enabled;
  if (is autopay is enabled for loan?) then (yes)
    #lightpink:show user autopay is enabled;
    detach
  else (no)
    :show autopay button;
    :user clicks button;
    #lightgreen: is taken to the autopay flow for that loan;
    detach
    endif
else (has multiple loans)
  if (is autopay is enabled for all?) then (yes)
     #lightpink:show user autopay is enabled;
    detach
  elseif (is autopay enabled for any loans?) then (yes)
    :show autopay button;
    :user clicks button;
    #lightblue: user is taken to the manage tab;
    detach
  else (no)
    :show autopay button;
    :user clicks button;
    #lightblue: is taken to the manage tab;
    detach
    endif
endif
@enduml